"use strict";
//        operators   \\
Object.defineProperty(exports, "__esModule", { value: true });
//   10 lines assignment of each operator
//          addition                  
let a = 10;
let b = 2;
let sum = a + b;
console.log(sum);
let sum0 = 34;
let sum1 = 24;
let totall = sum0 + sum1;
console.log(totall);
let summ = 12;
let summ1 = 12;
let tota11 = summ + summ1;
console.log(tota11);
let add = 6;
let add1 = 9;
let addition = add + add1;
console.log(addition);
let num = 10;
let num1 = 2;
let summ2 = num + num1;
console.log(summ2);
let a1 = 10;
let b2 = 12;
let ab3 = a1 + b2;
console.log(ab3);
let a0 = 19;
let b1 = 19;
let ab0 = a0 + b1;
console.log(ab0);
let numm = 29;
let numm1 = 13;
let number = numm + numm1;
console.log(number);
let c = 20;
let d = 19;
let cd = c + d;
console.log(cd);
let c1 = 66;
let d1 = 13;
let cd1 = c1 + d1;
console.log(cd1);
//   10 lines assignment of subtraction   \\
let subtraction = 18;
let subtraction1 = 9;
let subtraction2 = subtraction - subtraction1;
console.log(subtraction2);
let subt = 77;
let subtr = 66;
let subtr1 = subt - subtr;
console.log(subtr1);
let subt1 = 34;
let subt2 = 16;
let sub1 = subt1 - subt2;
console.log(sub1);
let subt0 = 13;
let subtr3 = 12;
let sub03 = subt0 - subtr3;
console.log(sub03);
let sub = 43;
let sub2 = 12;
let sub3 = sub - sub2;
console.log(sub3);
let minus = 66;
let minus1 = 44;
let minus2 = minus - minus1;
console.log(minus2);
let ab = 13;
let bd = 5;
let ad = ab - bd;
console.log(ad);
let min = 38;
let minu = 18;
let minuss = min - minu;
console.log(minuss);
let mins = 91;
let mins1 = 82;
let mins3 = mins - mins1;
console.log(mins3);
let mint = 45;
let mints = 14;
let tottall = mint - mints;
console.log(tottall);
// assignment of multiplication 
let multi = 2;
let multi1 = 2;
console.log(multi * multi1);
let multi2 = 3;
let multi3 = 2;
console.log(multi2 * multi3);
let mul = 5;
let mul1 = 5;
console.log(mul * mul1);
let mul0 = 8;
let mul2 = 5;
console.log(mul0 * mul2);
let m1 = 2;
let m2 = 9;
console.log(m1 * m2);
let m10 = 3;
let m20 = 7;
console.log(m10 * m20);
let m100 = 7;
let m200 = 9;
console.log(m100 * m200);
let m11 = 16;
let m22 = 2;
console.log(m11 * m22);
let m01 = 12;
let m02 = 1;
console.log(m01 * m02);
let m03 = 10;
let m04 = 10;
console.log(m03 * m04);
// assignment of  division 
let div = 12;
let div1 = 2;
console.log(div / div1);
let div0 = 77;
let div2 = 3;
console.log(div0 / div2);
let divi = 17;
let divi1 = 4;
console.log(divi / divi1);
let divi0 = 15;
let divi3 = 2;
console.log(divi0 / divi3);
let di = 88;
let di1 = 4;
console.log(di / di1);
let di2 = 8;
let di3 = 2;
console.log(di2 / di3);
let divis = 22;
let divid = 5;
console.log(divis / divid);
let divided = 6;
let division = 2;
console.log(divided / division);
let divi4 = 13;
let divi5 = 2;
console.log(divi4 / divi5);
let d0 = 66;
let d9 = 6;
console.log(d0 / d9);
